### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by yhatt** [speee/jsx-slack#20]
Now we have too long README.md to explain our features. jsx-slack must have a well-organized documentation to use easily.

### ToDo

- [ ] Migrate documentation from README.md to the other hosted site
- [ ] Add more useful usages
  - [ ] Prefer using template literal to using JSX transpiler as a basic usage
  - [ ] Add how to define custom block
