### ISSUE TITLE
Modals support

### ISSUE THREAD

**Issue by yhatt** [speee/jsx-slack#57]
Slack has announced new surface for Block Kit called **Modals**. It provides the second place to show Block Kit contents, and the first-class Block Kit support within dialog.

https://api.slack.com/block-kit/surfaces/modals

We've already supported the classic `<Dialog>` (#19), but it would be soft-deprecated in favor of Modals. Some interfaces for Dialog components would be able to apply into Modals too. (`<Input>`, `<Textarea>`, etc...)

### ToDo

- [x] Consider interface
- [x] Add Modals support to main entry
  - [x] Add attributes for Modals to existing components
  - [x] `<Input>` block
    - [x] Add HTML-like components based on existing dialog support
    - [x] Add intrinsic elements for aliasing to added components
- [x] Soft-deprecate `@speee-js/jsx-slack/dialog` entry point
  - Don't mention the classic dialog support in README, but existing user can use entrypoint without warning
- [x] Update schema for demo
